"use client";
import { StyledEngineProvider } from "@mui/material/styles";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import axios from "axios";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Provider } from "react-redux";
import store from "../redux/store";
import "./globals.css";
const queryClient = new QueryClient();
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  useEffect(() => {
    async function checkCookie() {
      let token = JSON.parse(localStorage.getItem("token"));
      await axios
        .post(
          "http://localhost:4000/auth/checkAuth",
          { token },
          { withCredentials: true }
        )
        .then((res) => {
          if (!res.data.success) {
            localStorage.removeItem("token");
            router.push("/signin");
          }
        });
    }
    checkCookie();
  }, []);
  return (
    <html lang="en">
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <body className={`lexend`}>
            <StyledEngineProvider injectFirst>{children}</StyledEngineProvider>
          </body>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </Provider>
    </html>
  );
}
